fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppet: "git://github.com/theforeman/puppet-puppet.git"
    puppetmaster: "git://github.com/attachmentgenie/attachmentgenie-puppetmaster.git"
    epel: "git://github.com/stahnma/puppet-module-epel.git"
    ntp: "git://github.com/puppetlabs/puppetlabs-ntp.git"
    selinux: "git://github.com/jfryman/puppet-selinux.git"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    puppetdb: "git://github.com/puppetlabs/puppetlabs-puppetdb.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    foreman: "git://github.com/theforeman/puppet-foreman.git"
    foreman_proxy: "git://github.com/theforeman/puppet-foreman_proxy.git"
    tftp: "git://github.com/theforeman/puppet-tftp.git"
    mcollective: "git://github.com/puppet-community/puppet-mcollective.git"
    datacat: "git://github.com/richardc/puppet-datacat.git"
    activemq: "git://github.com/puppetlabs/puppetlabs-activemq.git"
    orchestrate: "git://github.com/attachmentgenie/attachmentgenie-orchestrate.git"
    timezone: "git://github.com/attachmentgenie/attachmentgenie-timezone.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    r10k: "git://github.com/acidprime/r10k.git"
    git: "git://github.com/puppetlabs/puppetlabs-git.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    extlib: "git://github.com/puppet-community/puppet-extlib.git"
  symlinks:
    "puppetmaster": "#{source_dir}"
